version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patches:
        update-types: ["patch"]
    open-pull-requests-limit: 5
