/* LLMOSAFE: Safety-Critical AI Agent Library (C Bindings) */

#ifndef LLMOSAFE_H
#define LLMOSAFE_H

#pragma once

/* This file is automatically generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>







#define Privilege_CAP_SANDBOX (1 << 0)

#define Privilege_CAP_ROOT (1 << 1)

#define Privilege_CAP_NETWORK (1 << 2)

typedef struct Privilege Privilege;

/**
 * The "Synapse" (Binary Cognitive Protocol).
 * A bit-packed u64 carrying the entire stability state.
 * [Entropy: 16][Surprise: 16][Bias: 1][Hash: 31]
 *
 * #[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]Examples
 *
 * ```
 * use llmosafe::Synapse;
 * let synapse = Synapse::new(); // Provided by bitfield
 * ```
 */
typedef struct Synapse Synapse;

/**
 * VitalsReport (C-compatible) for the Mycelial Introspection ABI.
 */
typedef struct VitalsReport {
    double iowait_percent;
    double load_avg_1min;
} VitalsReport;

#define STABILITY_THRESHOLD 1000

/**
 * Process a single Synapse spike into the global working memory.
 * Returns 0 on success, or a negative error code on failure.
 * -1: Depth Exceeded
 * -2: Cognitive Instability (Entropy too high)
 * -3: Bias/Halo Detected
 * -4: Hallucination Detected (Surprise too high)
 */
int32_t llmosafe_process_synapse(uint64_t synapse_bits);

/**
 * Calculate the halo signal for a given piece of text.
 * Higher values indicate higher probability of cognitive shortcut bias.
 */
uint16_t llmosafe_calculate_halo(const char *text_ptr);

/**
 * Check resource usage against a ceiling (in MB).
 * Creates a ResourceGuard with the specified ceiling and checks current usage.
 * Returns 0 on success (resources within bounds), or -5 on ResourceExhaustion.
 */
int32_t llmosafe_check_resources(uint32_t ceiling_mb);

/**
 * Capability Ledger: Authorize a specific kernel action.
 * Actions: 0 = IndexRoot, 1 = ExternalApiCall, 2 = StandardProcessing
 * Returns 0 if authorized, or -6 if PermissionDenied.
 */
int32_t llmosafe_authorize_action(int32_t action_id);

/**
 * Mycelial Sense: Query current system vitals.
 */
struct VitalsReport llmosafe_sense_vitals(void);

/**
 * Mycelial Sense: Query current capability bitmask.
 */
uint64_t llmosafe_sense_capabilities(void);

/**
 * Metabolic Law: Enforce pacing of reasoning steps.
 * min_interval_ms: Minimum time between steps in milliseconds.
 * Returns 0 on success, or -2 if CognitiveInstability (pacing violation).
 */
int32_t llmosafe_metabolic_pace(uint64_t min_interval_ms);

#endif  /* LLMOSAFE_H */
